version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
    ports:
      - '80:80'
  php:
    build:
      context: .
      dockerfile: docker/php/php.Dockerfile
    volumes:
      - ./app:/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_DATABASE: 'test'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysqldata: {}
